Campaign Card Display
bachpx-vbee/Campaign-Client pull request #23
Opened 2023-06-22 02:35 UTC by Ngoccccc

2023-06-27 01:26 UTC, lamndh-vbee commented on src/components/CampaignCard/index.jsx
> +function CampaignCard({ campaign }) {
{ campaign } => props
const { campaign } = props

2023-06-29 01:36 UTC, bachpx-vbee commented on src/components/CampaignCard/index.jsx
> +function CampaignCard({ campaign }) {
cả arrow function nữa

2023-07-05 09:52 UTC, bachpx-vbee commented on src/components/CampaignCard/index.jsx
> +const CampaignCard = ({ props }) => {
props thôi, không phải { props }

2023-07-06 03:21 UTC, lamndh-vbee commented on src/components/CampaignCard/index.jsx
> +        <Button size="small" onClick={() => handleOpenDetail()}>
onClick={handleOpenDetail}

2023-07-11 03:02 UTC, lamndh-vbee requested changes

2023-07-11 03:02 UTC, lamndh-vbee commented on src/components/CampaignCard/index.jsx
> +          {/* <Link underline="none" href={`/campaign/${campaign.id}`}>
Em dùng Link code tiếp nhé anh chưa tìm ra vấn đề

2023-07-11 03:02 UTC, lamndh-vbee commented on src/constants/route.js
> +  TEST: "/campaign/:id"
Đổi tên

2023-07-11 03:02 UTC, lamndh-vbee commented on src/components/CampaignCard/Test.jsx
> +const Test = () => {
Đổi tên

2023-07-13 08:29 UTC, lamndh-vbee requested changes

2023-07-13 08:29 UTC, lamndh-vbee commented on src/components/CampaignCard/index.jsx
> +  console.log(campaign);
remove log

2023-07-13 08:43 UTC, lamndh-vbee approved these changes

2023-07-13 08:44 UTC, merged